version: '3.5'

services:
  api:
    build: api/
    ports:
      - '${SERVER_PORT}:${API_PORT}'
    environment:
      - API_HOSTNAME
      - API_PORT
      - API_SECURE
      - API_VERSION
    restart: unless-stopped
