spring:
  webflux:
    base-path: /api/v1

server:
  port: 8080

api:
  hostname: localhost
  port: 8080
  secure: true
  version: v1

springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /docs
