version: '3.5'

services:
  api:
    build: api/
    ports:
      - '${SERVER_PORT}:${API_PORT}'
    environment:
      - API_PORT
      - API_VERSION
      - API_SQUARE_METER_PRICE
    restart: unless-stopped
